[package]
name = "imhd-HPC"
version = "0.1.0"
edition = "2021"

authors = ["Matt Russell russellmatt66@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
